### ISSUE TITLE
RuntimeError: The size of tensor a (32001) must match the size of tensor b (32000) at non-singleton dimension 1

### ISSUE THREAD

**Issue by kirudang** [jthickstun/watermark#6]
Hello,

I have generated the watermarked outputs for two models:
OPT 125M and Llama 2 7B.
While it works well with OPT, the Llama 2 has error, which is a bit weird. 

The error comes from this function:
```
def exp_sampling(probs,u):
    return torch.argmax(u ** (1/probs),axis=1).unsqueeze(-1)
```
The error:
```
Traceback (most recent call last):
  File "/network/rit/lab/Lai_ReSecureAI/kiel/rdf_wm2/generate_llama2.py", line 143, in <module>
    main(parser.parse_args())
  File "/network/rit/lab/Lai_ReSecureAI/kiel/rdf_wm2/generate_llama2.py", line 81, in main
    outputs = generate_shift(model, prompt_tokens, len(tokenizer), args.n, args.m, args.key)[0]
  File "/network/rit/lab/Lai_ReSecureAI/kiel/rdf_wm2/generate_llama2.py", line 31, in generate_shift
    token = exp_sampling(probs,xi[(shift+i)%n,:]).to(model.device)
  File "/network/rit/lab/Lai_ReSecureAI/kiel/rdf_wm2/generate_llama2.py", line 40, in exp_sampling
    return torch.argmax(u ** (1/probs),axis=1).unsqueeze(-1)
  File "/network/rit/lab/Lai_ReSecureAI/kiel/anaconda3/envs/new_env/lib/python3.10/site-packages/torch/_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
RuntimeError: The size of tensor a (32001) must match the size of tensor b (32000) at non-singleton dimension 1
```
Could you help me check?

**Comment by RohithKuditipudi** [comment]
Hi - can you send the command you're running so we can try to reproduce?

**Comment by kirudang** [comment]
Hello, I already solved it
```
    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    print(f"Tokenizer vocabulary size: {len(tokenizer)}")

    # Model
    model = AutoModelForCausalLM.from_pretrained(args.model).to(device)
    model.resize_token_embeddings(len(tokenizer))  # Resize the token embeddings
    print(f"Model's vocabulary size: {model.config.vocab_size}")
```

Results:
```
Tokenizer vocabulary size: 32001
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.20s/it]
Model's vocabulary size: 32000
```
This is because Llama 2 has some special token PAD, so we need to resize the two to make sure they have the same vocab size
